project:
  type: website
  output-dir: docs
  preview: 
    watch-inputs: false

website:
  title: "conservationdatalab.org"
  navbar:
    search: TRUE
    pinned: true
    right:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: People
      - href: blog.qmd
        text: Blog
      - href: participate.qmd
        text: Participate
      - href: about.qmd
        text: About

      
format:
  html:
    theme: 
      light: flatly
css: styles.css


        
        
        
        